model:
  params:
    # embed_dim: 1024
    condconfig:
      context_dim: 256
    ddconfig:
      double_z: False
      z_channels: 3
      resolution: 128
      in_channels: 1
      out_ch: 1
      ch: 16 ## original 64
      ch_mult: [1,2,2,4]  # num_down = len(ch_mult)-1
      # ch_mult: [1,2,2,4]  # num_down = len(ch_mult)-1
      # ch_mult: [1,2,4]  # num_down = len(ch_mult)-1
      num_res_blocks: 1
      attn_resolutions: []
      dropout: 0.0

lossconfig:
  loss_weight_annealing: False
  params:
    recon_weight: 1.0
    kld_weight: 1.0
